### ISSUE TITLE
MatrixMN.cpp의 get1DIndex() 함수에 assert 조건 에러

### ISSUE THREAD

**Issue by jangsoopark** [jmhong-simulation/FCNN#1]
MatrixMN.cpp, line 100
assert(row < num_cols_); 을 
assert(column < num_cols_); 로 하는게 맞는것 같습니다.

좋은 튜토리얼 감사합니다.

https://github.com/jmhong-simulation/FCNN/blob/5f125197016a017d6567e3a630fa2793e9bd242a/MatrixMN.cpp#L100

**Comment by jmhong-simulation** [comment]
엇 그렇네요. 감사합니다.
